Controllers/DemandesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestion_des_visiteurs;
using gestion_des_visiteurs.Models;

namespace gestion_des_visiteurs.Controllers
{
    public class DemandesController : Controller
    {
        private readonly gestion_des_visiteursDbContext _context;

        public DemandesController(gestion_des_visiteursDbContext context)
        {
            _context = context;
        }

        // GET: Demandes
        public async Task<IActionResult> Index()
        {
            var gestion_des_visiteursDbContext = _context.Demandes.Include(d => d.Superviseur).Include(d => d.Visiteur);
            return View(await gestion_des_visiteursDbContext.ToListAsync());
        }

        // GET: Demandes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var demande = await _context.Demandes
                .Include(d => d.Superviseur)
                .Include(d => d.Visiteur)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (demande == null)
            {
                return NotFound();
            }

            return View(demande);
        }

        // GET: Demandes/Create
        public IActionResult Create()
        {
            ViewData["idSuperviseur"] = new SelectList(_context.Superviseurs, "Id", "nom");
            ViewData["idVisiteur"] = new SelectList(_context.Visiteurs, "Id", "nom");
            return View();
        }

        // POST: Demandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("nom,description,idVisiteur,idSuperviseur")] Demande demande)
        {
            if (ModelState.IsValid)
            {
                var p = await _context.Visiteurs
               .FirstOrDefaultAsync(m => m.Id == demande.idVisiteur);
                demande.Visiteur = p ?? new Visiteur();

                var o = await _context.Superviseurs
               .FirstOrDefaultAsync(m => m.Id == demande.idSuperviseur);
                demande.Superviseur = o ?? new Superviseur();

                _context.Add(demande);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["idSuperviseur"] = new SelectList(_context.Superviseurs, "Id", "cin", demande.idSuperviseur);
            ViewData["idVisiteur"] = new SelectList(_context.Visiteurs, "Id", "cin", demande.idVisiteur);
            return View(demande);
        }

        // GET: Demandes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var demande = await _context.Demandes.FindAsync(id);
            if (demande == null)
            {
                return NotFound();
            }
            ViewData["idSuperviseur"] = new SelectList(_context.Superviseurs, "Id", "cin", demande.idSuperviseur);
            ViewData["idVisiteur"] = new SelectList(_context.Visiteurs, "Id", "cin", demande.idVisiteur);
            return View(demande);
        }

        // POST: Demandes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,nom,description,idVisiteur,idSuperviseur")] Demande demande)
        {
            if (id != demande.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(demande);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DemandeExists(demande.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["idSuperviseur"] = new SelectList(_context.Superviseurs, "Id", "cin", demande.idSuperviseur);
            ViewData["idVisiteur"] = new SelectList(_context.Visiteurs, "Id", "cin", demande.idVisiteur);
            return View(demande);
        }

        // GET: Demandes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var demande = await _context.Demandes
                .Include(d => d.Superviseur)
                .Include(d => d.Visiteur)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (demande == null)
            {
                return NotFound();
            }

            return View(demande);
        }

        // POST: Demandes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var demande = await _context.Demandes.FindAsync(id);
            if (demande != null)
            {
                _context.Demandes.Remove(demande);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DemandeExists(int id)
        {
            return _context.Demandes.Any(e => e.Id == id);
        }
    }
}

Controllers/VisitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestion_des_visiteurs;
using gestion_des_visiteurs.Models;

namespace gestion_des_visiteurs.Controllers
{
    public class VisitesController : Controller
    {
        private readonly gestion_des_visiteursDbContext _context;

        public VisitesController(gestion_des_visiteursDbContext context)
        {
            _context = context;
        }

        // GET: Visites
        public async Task<IActionResult> Index()
        {
            return View(await _context.Visites.ToListAsync());
        }

        // GET: Visites/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visite = await _context.Visites
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visite == null)
            {
                return NotFound();
            }

            return View(visite);
        }

        // GET: Visites/Create
        public IActionResult Create()
        {
            ViewData["idVisiteur"] = new SelectList(_context.Visiteurs, "Id", "nom");
            return View();
        }

        // POST: Visites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("dateVisite,heureDebut,heureFin,duree,idVisiteur")] Visite visite)
        {
            if (ModelState.IsValid)
            {
                var p = await _context.Visiteurs
               .FirstOrDefaultAsync(m => m.Id == visite.idVisiteur);
                visite.Visiteur = p ?? new Visiteur();
                _context.Add(visite);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(visite);
        }

        // GET: Visites/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visite = await _context.Visites.FindAsync(id);
            if (visite == null)
            {
                return NotFound();
            }
            return View(visite);
        }

        // POST: Visites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,dateVisite,heureDebut,heureFin,duree,idVisiteur")] Visite visite)
        {
            if (id != visite.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisiteExists(visite.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(visite);
        }

        // GET: Visites/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visite = await _context.Visites
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visite == null)
            {
                return NotFound();
            }

            return View(visite);
        }

        // POST: Visites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var visite = await _context.Visites.FindAsync(id);
            if (visite != null)
            {
                _context.Visites.Remove(visite);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisiteExists(int id)
        {
            return _context.Visites.Any(e => e.Id == id);
        }
    }
}

Controllers/VisiteursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestion_des_visiteurs;
using gestion_des_visiteurs.Models;

namespace gestion_des_visiteurs.Controllers
{
    public class VisiteursController : Controller
    {
        private readonly gestion_des_visiteursDbContext _context;

        public VisiteursController(gestion_des_visiteursDbContext context)
        {
            _context = context;
        }

        // GET: Visiteurs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Visiteurs.ToListAsync());
        }

        // GET: Visiteurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visiteur = await _context.Visiteurs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visiteur == null)
            {
                return NotFound();
            }

            return View(visiteur);
        }

        // GET: Visiteurs/Create
        public IActionResult Create()
        {
            ViewData["idSuperviseur"] = new SelectList(_context.Superviseurs, "Id", "nom");
            return View();
        }

        // POST: Visiteurs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,nom,prenom,email,telephone,cin,idSuperviseur")] Visiteur visiteur)
        {
            if (ModelState.IsValid)
            {
                var p = await _context.Superviseurs
               .FirstOrDefaultAsync(m => m.Id == visiteur.idSuperviseur);
                visiteur.Superviseur = p ?? new Superviseur();
                _context.Add(visiteur);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(visiteur);
        }

        // GET: Visiteurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visiteur = await _context.Visiteurs.FindAsync(id);
            if (visiteur == null)
            {
                return NotFound();
            }
            return View(visiteur);
        }

        // POST: Visiteurs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,nom,prenom,email,telephone,cin,idSuperviseur")] Visiteur visiteur)
        {
            if (id != visiteur.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visiteur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisiteurExists(visiteur.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(visiteur);
        }

        // GET: Visiteurs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visiteur = await _context.Visiteurs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visiteur == null)
            {
                return NotFound();
            }

            return View(visiteur);
        }

        // POST: Visiteurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var visiteur = await _context.Visiteurs.FindAsync(id);
            if (visiteur != null)
            {
                _context.Visiteurs.Remove(visiteur);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisiteurExists(int id)
        {
            return _context.Visiteurs.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - gestion_des_visiteurs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/gestion_des_visiteurs.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="home" asp-action="index">
                <img src="~/images/logo1.png" />
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Superviseurs" asp-action="Index">Superviseurs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Administrateurs" asp-action="Index">Administrateurs</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="dropdown-item" asp-area="" asp-controller="Visiteurs" asp-action="Index" onmouseover="drop()">Visiteurs</a>
                        <ul class="dropdown-menu" id="list">
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Visites" asp-action="Index">Visites</a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Demandes" asp-action="Index">Demandes</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <footer>
            <div class="container">
                <div class="footer-container">
                    <h3>Liens</h3>
                    <ul class="list">
                        <li><a asp-area="" asp-controller="Superviseurs" asp-action="Index">Superviseurs</a></li>
                        <li><a asp-area="" asp-controller="Administrateur" asp-action="Index">Administrateurs</a></li>
                        <li><a asp-area="" asp-controller="Visiteurs" asp-action="Index">Visiteurs</a></li>
                        <li><a asp-area="" asp-controller="Demandes" asp-action="Index">Demandes</a></li>
                        <li><a asp-area="" asp-controller="Visites" asp-action="Index">Visites</a></li>
                    </ul>
                </div>
                <div class="footer-container">
                    <h3>Contact</h3>
                    <p>Hamilton Avenue San Jose,<br /> California 95125 USA</p>
                    <p>646-536-2842</p>
                </div>
                <div class="footer-container">
                    <h3>Réseaux sociaux</h3>
                    <ul class="social-icons">
                        <li><a href=""><img src="~/images/facebook.png" /></a></li>
                        <li><a href=""><img src="~/images/instagram.png" /></a></li>
                        <li><a href=""><img src="~/images/twitter.png" /></a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function drop(){
            let list = document.getElementById("list");
            list.display = block;
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>